// Code generated by scripts/gen_vectors.py using zigpy 1.4.1. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.

pub static ROUNDTRIP_RAW: &[(&[u8], u32)] = &[
    (&[0x00, 0x00, 0x00, 0x00], 0u32),
    (&[0x01, 0x00, 0x00, 0x00], 1u32),
    (&[0xAA, 0x00, 0x00, 0x00], 170u32),
    (&[0xFF, 0xFF, 0xFF, 0xFF], 4294967295u32),
];
