// Code generated by scripts/gen_vectors.py using zigpy 1.4.1. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.

pub static ROUNDTRIP_RAW: &[(&[u8], u16)] = &[
    (&[0x00, 0x00], 0u16),
    (&[0x01, 0x00], 1u16),
    (&[0xAA, 0x00], 170u16),
    (&[0xFF, 0xFF], 65535u16),
];
