// Code generated by scripts/gen_vectors.py using zigpy 1.4.1. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.

pub static ROUNDTRIP: &[(&[u8], bool)] = &[(&[0x00], false), (&[0x01], true)];

pub static NULL_WIRE: &[&[u8]] = &[&[0xFF]];

/// These must return Err(ZclError::InvalidValue), not NullSentinel.
pub static INVALID_VALUE: &[&[u8]] = &[&[0x02], &[0xFE]];
