// Code generated by scripts/gen_vectors.py using zigpy 1.4.1. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.

/// Compare decoded f32 bits via f32::to_bits() to avoid NaN != NaN.
pub static ROUNDTRIP_BITS: &[(&[u8], u32)] = &[
    (&[0x00, 0x00, 0x00, 0x00], 0u32),
    (&[0x00, 0x00, 0x80, 0x3F], 1065353216u32),
    (&[0x00, 0x00, 0x80, 0xBF], 3212836864u32),
    (&[0x00, 0x00, 0xC0, 0x3F], 1069547520u32),
];

pub static NULL_WIRE: &[&[u8]] = &[&[0x00, 0x00, 0xC0, 0x7F]];
