// Code generated by scripts/gen_vectors.py using zigpy 1.4.1. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.

pub static ROUNDTRIP: &[(&[u8], i16)] = &[
    (&[0x00, 0x00], 0i16),
    (&[0x01, 0x00], 1i16),
    (&[0xFF, 0xFF], -1i16),
    (&[0xFF, 0x7F], 32767i16),
    (&[0x01, 0x80], -32767i16),
];

pub static NULL_WIRE: &[&[u8]] = &[&[0x00, 0x80]];
