// Code generated by scripts/gen_vectors.py using zigpy 1.4.1. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.

pub static ROUNDTRIP: &[(&[u8], i8)] = &[
    (&[0x00], 0i8),
    (&[0x01], 1i8),
    (&[0xFF], -1i8),
    (&[0x7F], 127i8),
    (&[0x81], -127i8),
];

pub static NULL_WIRE: &[&[u8]] = &[&[0x80]];
