// Code generated by scripts/gen_vectors.py using zigpy 1.4.1. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.

pub static VALID: &[&[u8]] = &[
    &[0x20, 0x02, 0x00, 0x01, 0x02],
    &[0x20, 0x03, 0x00, 0x0A, 0x0B, 0x0C],
];

/// Must return Err(ZclError::InvalidValue) — duplicate elements.
pub static DUPLICATE_ELEMENT: &[&[u8]] = &[&[0x20, 0x02, 0x00, 0x01, 0x01]];
