// Code generated by scripts/gen_vectors.py using zigpy 1.4.1. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.

pub static ROUNDTRIP: &[(&[u8], &[u8])] = &[
    (&[0x00], b""),
    (&[0x01, 0x00], b"\x00"),
    (&[0x04, 0xDE, 0xAD, 0xBE, 0xEF], b"\xDE\xAD\xBE\xEF"),
];

pub static NULL_WIRE: &[&[u8]] = &[&[0xFF]];
