// Code generated by scripts/gen_vectors.py using zigpy 1.4.1. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.

pub static ROUNDTRIP: &[(&[u8], &str)] = &[
    (&[0x00], ""),
    (&[0x05, 0x68, 0x65, 0x6C, 0x6C, 0x6F], "hello"),
    (&[0x05, 0x63, 0x61, 0x66, 0xC3, 0xA9], "café"),
];

pub static NULL_WIRE: &[&[u8]] = &[&[0xFF]];

/// Must return Err(ZclError::InvalidUtf8).
pub static INVALID_UTF8: &[&[u8]] = &[&[0x03, 0xFF, 0xFE, 0xFD]];
