// Code generated by scripts/gen_vectors.py using zigpy 1.4.1. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.

pub static ROUNDTRIP: &[(&[u8], u16)] = &[
    (&[0x00, 0x00], 0u16),
    (&[0x01, 0x00], 1u16),
    (&[0x00, 0x80], 32768u16),
    (&[0xFE, 0xFF], 65534u16),
];

pub static NULL_WIRE: &[&[u8]] = &[&[0xFF, 0xFF]];
