// Code generated by scripts/gen_vectors.py using zigpy 1.4.1. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.

pub static ROUNDTRIP: &[(&[u8], u32)] = &[
    (&[0x00, 0x00, 0x00, 0x00], 0u32),
    (&[0x01, 0x00, 0x00, 0x00], 1u32),
    (&[0x00, 0x00, 0x00, 0x80], 2147483648u32),
    (&[0xFE, 0xFF, 0xFF, 0xFF], 4294967294u32),
];

pub static NULL_WIRE: &[&[u8]] = &[&[0xFF, 0xFF, 0xFF, 0xFF]];
