// Code generated by scripts/gen_vectors.py using zigpy 1.4.1. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.

pub static ROUNDTRIP: &[(&[u8], u8)] = &[
    (&[0x00], 0u8),
    (&[0x01], 1u8),
    (&[0x80], 128u8),
    (&[0xFE], 254u8),
];

pub static NULL_WIRE: &[&[u8]] = &[&[0xFF]];
