// Code generated by scripts/gen_vectors.py using zigpy 1.4.1. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.

pub static ROUNDTRIP: &[(&[u8], &[i16])] = &[
    (&[0x29, 0x00, 0x00], &[]),
    (&[0x29, 0x01, 0x00, 0xFF, 0xFF], &[-1i16]),
    (
        &[0x29, 0x03, 0x00, 0x00, 0x00, 0x64, 0x00, 0x9C, 0xFF],
        &[0i16, 100i16, -100i16],
    ),
];

pub static NULL_WIRE: &[&[u8]] = &[&[0x29, 0xFF, 0xFF]];

/// Must return Err(ZclError::TypeIdMismatch) — element_type byte is wrong.
pub static TYPE_MISMATCH: &[&[u8]] = &[&[0x20, 0x01, 0x00, 0x00, 0x00]];
