// Code generated by scripts/gen_vectors.py using zigpy 1.4.1. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.

pub static VALID: &[(&[u8], &[u16])] = &[
    (&[0x21, 0x02, 0x00, 0x01, 0x00, 0x02, 0x00], &[1u16, 2u16]),
    (
        &[0x21, 0x03, 0x00, 0x0A, 0x00, 0x14, 0x00, 0x1E, 0x00],
        &[10u16, 20u16, 30u16],
    ),
];

/// Must return Err(ZclError::InvalidValue) — duplicate elements.
pub static DUPLICATE: &[&[u8]] = &[&[0x21, 0x02, 0x00, 0x01, 0x00, 0x01, 0x00]];
