// Code generated by scripts/gen_vectors.py using zigpy 1.4.1. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.

pub static VALID: &[(&[u8], &[u8])] = &[
    (&[0x20, 0x02, 0x00, 0x01, 0x02], &[1u8, 2u8]),
    (&[0x20, 0x03, 0x00, 0x0A, 0x0B, 0x0C], &[10u8, 11u8, 12u8]),
];

/// Must return Err(ZclError::InvalidValue) — duplicate elements.
pub static DUPLICATE: &[&[u8]] = &[&[0x20, 0x02, 0x00, 0x01, 0x01]];
