// Code generated by scripts/gen_vectors.py using zigpy 1.4.1. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.

/// (wire, (u8_field, array_field_elements))
pub static ROUNDTRIP: &[(&[u8], (u8, &[u8]))] = &[
    (
        &[0x02, 0x00, 0x20, 0x00, 0x48, 0x20, 0x00, 0x00],
        (0u8, &[]),
    ),
    (
        &[
            0x02, 0x00, 0x20, 0x2A, 0x48, 0x20, 0x03, 0x00, 0x01, 0x02, 0x03,
        ],
        (42u8, &[1u8, 2u8, 3u8]),
    ),
    (
        &[0x02, 0x00, 0x20, 0xFE, 0x48, 0x20, 0x02, 0x00, 0x0A, 0x14],
        (254u8, &[10u8, 20u8]),
    ),
];

pub static NULL_WIRE: &[&[u8]] = &[&[0xFF, 0xFF]];
