# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "zigpy==1.4.1",
# ]
# ///
"""
ZCL test vector generator.

Uses zigpy as the reference implementation to produce byte-exact
encodings for each ZCL type supported by zigbee-cluster-library.

Run via xtask (preferred):
    cargo xtask generate-vectors   # write to zigbee-cluster-library/tests/vectors/
    cargo xtask check-vectors      # diff against committed vectors; exit 1 on drift

Or directly:
    uv run scripts/gen_vectors.py --out zigbee-cluster-library/tests/vectors/
    uv run scripts/gen_vectors.py --out /tmp/check --check
"""

import argparse
import difflib
import importlib.metadata
import struct
import sys
from pathlib import Path

import zigpy.types as t

ZIGPY_VERSION = importlib.metadata.version("zigpy")

HEADER = f"""\
// Code generated by scripts/gen_vectors.py using zigpy {ZIGPY_VERSION}. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.
"""

def fmt_bytes(b: bytes) -> str:
    return "&[" + ", ".join(f"0x{byte:02X}" for byte in b) + "]"


def fmt_roundtrip_scalar(pairs: list[tuple[bytes, str]], rust_type: str) -> str:
    lines = [f"    ({fmt_bytes(wire)}, {val}{rust_type})," for wire, val in pairs]
    return (
        f"pub static ROUNDTRIP: &[(&[u8], {rust_type})] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )


def fmt_roundtrip_bool(pairs: list[tuple[bytes, str]]) -> str:
    lines = [f"    ({fmt_bytes(wire)}, {val})," for wire, val in pairs]
    return (
        "pub static ROUNDTRIP: &[(&[u8], bool)] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )


def fmt_bytes_list(name: str, items: list[bytes]) -> str:
    lines = [f"    {fmt_bytes(b)}," for b in items]
    return f"pub static {name}: &[&[u8]] = &[\n" + "\n".join(lines) + "\n];\n"


def fmt_roundtrip_bits(pairs: list[tuple[bytes, str]], rust_type: str, inner: str) -> str:
    """For bitmaps: store as (wire, u64 raw value) since the Rust type is a newtype."""
    lines = [f"    ({fmt_bytes(wire)}, {val}{inner})," for wire, val in pairs]
    return (
        f"pub static ROUNDTRIP_RAW: &[(&[u8], {inner})] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )


def assemble(*sections: str) -> str:
    return HEADER + "\n" + "\n".join(s for s in sections if s)


def gen_uint(zigpy_type, rust_type: str, bits: int) -> str:
    max_valid = (1 << bits) - 2  # one below null sentinel
    null_val = (1 << bits) - 1

    values = [0, 1, max_valid // 2 + 1, max_valid]
    roundtrip = [
        (zigpy_type(v).serialize(), str(v))
        for v in values
    ]
    null_wire = zigpy_type(null_val).serialize()

    return assemble(
        fmt_roundtrip_scalar(roundtrip, rust_type),
        fmt_bytes_list("NULL_WIRE", [null_wire]),
    )


def gen_sint(zigpy_type, rust_type: str, bits: int) -> str:
    null_val = -(1 << (bits - 1))   # e.g. -128 for i8
    max_val = (1 << (bits - 1)) - 1  # e.g. 127

    values = [0, 1, -1, max_val, null_val + 1]  # null+1 = one above sentinel
    roundtrip = [
        (zigpy_type(v).serialize(), str(v))
        for v in values
    ]
    null_wire = zigpy_type(null_val).serialize()

    return assemble(
        fmt_roundtrip_scalar(roundtrip, rust_type),
        fmt_bytes_list("NULL_WIRE", [null_wire]),
    )


def gen_bool() -> str:
    # ZCL bool: 0x00 = false, 0x01 = true, 0xFF = null sentinel.
    roundtrip = [
        (t.Bool(False).serialize(), "false"),
        (t.Bool(True).serialize(), "true"),
    ]
    # Values that must return ZclError::InvalidValue, not NullSentinel.
    invalid = [bytes([0x02]), bytes([0xFE])]
    null_wire = bytes([0xFF])

    return assemble(
        fmt_roundtrip_bool(roundtrip),
        fmt_bytes_list("NULL_WIRE", [null_wire]),
        "/// These must return Err(ZclError::InvalidValue), not NullSentinel.\n"
        + fmt_bytes_list("INVALID_VALUE", invalid),
    )


def gen_f32() -> str:
    # Roundtrip stored as raw bit patterns (u32) to avoid float equality issues.
    vals: list[tuple[float, str]] = [
        (0.0, "0"),
        (1.0, str(struct.unpack('<I', struct.pack('<f', 1.0))[0])),
        (-1.0, str(struct.unpack('<I', struct.pack('<f', -1.0))[0])),
        (1.5, str(struct.unpack('<I', struct.pack('<f', 1.5))[0])),
    ]
    roundtrip_raw = [
        (t.Single(v).serialize(), bits)
        for v, bits in vals
    ]
    # ZCL Single Precision null = any NaN; the canonical zigpy NaN
    null_wire = t.Single(float("nan")).serialize()

    lines = [f"    ({fmt_bytes(wire)}, {bits}u32)," for wire, bits in roundtrip_raw]
    roundtrip_section = (
        "/// Compare decoded f32 bits via f32::to_bits() to avoid NaN != NaN.\n"
        "pub static ROUNDTRIP_BITS: &[(&[u8], u32)] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )
    return assemble(
        roundtrip_section,
        fmt_bytes_list("NULL_WIRE", [null_wire]),
    )


def gen_f64() -> str:
    vals: list[tuple[float, str]] = [
        (0.0, "0"),
        (1.0, str(struct.unpack('<Q', struct.pack('<d', 1.0))[0])),
        (-1.0, str(struct.unpack('<Q', struct.pack('<d', -1.0))[0])),
        (1.5, str(struct.unpack('<Q', struct.pack('<d', 1.5))[0])),
    ]
    roundtrip_raw = [
        (t.Double(v).serialize(), bits)
        for v, bits in vals
    ]
    null_wire = t.Double(float("nan")).serialize()

    lines = [f"    ({fmt_bytes(wire)}, {bits}u64)," for wire, bits in roundtrip_raw]
    roundtrip_section = (
        "/// Compare decoded f64 bits via f64::to_bits() to avoid NaN != NaN.\n"
        "pub static ROUNDTRIP_BITS: &[(&[u8], u64)] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )
    return assemble(
        roundtrip_section,
        fmt_bytes_list("NULL_WIRE", [null_wire]),
    )


def gen_bitmap(zigpy_type, rust_type: str, inner: str, bits: int) -> str:
    all_ones = (1 << bits) - 1
    values = [0, 1, 0b10101010, all_ones]
    roundtrip = [
        (zigpy_type(v).serialize(), str(v))
        for v in values
        if v <= all_ones
    ]
    # Bitmaps have no null sentinel; ALL_PATTERNS_VALID = true.
    return assemble(fmt_roundtrip_bits(roundtrip, rust_type, inner))


def gen_enum8() -> str:
    # Enum decode is user-driven (the Rust callback decides valid discriminants).
    # Vectors here test that the schema passes the raw byte through correctly;
    # application-level validation is tested in cluster-specific tests.
    roundtrip = [
        (t.enum8(v).serialize(), str(v))
        for v in [0x00, 0x01, 0x42, 0xFE]
    ]
    null_wire = t.enum8(0xFF).serialize()
    return assemble(
        fmt_roundtrip_scalar(roundtrip, "u8"),
        fmt_bytes_list("NULL_WIRE", [null_wire]),
    )


def gen_enum16() -> str:
    roundtrip = [
        (t.enum16(v).serialize(), str(v))
        for v in [0x0000, 0x0001, 0x0100, 0xFFFE]
    ]
    null_wire = t.enum16(0xFFFF).serialize()
    return assemble(
        fmt_roundtrip_scalar(roundtrip, "u16"),
        fmt_bytes_list("NULL_WIRE", [null_wire]),
    )


def gen_short_text() -> str:
    # Wire: [len: u8, utf8 bytes...]  null sentinel: len = 0xFF
    def encode(s: str) -> bytes:
        b = s.encode("utf-8")
        return bytes([len(b)]) + b

    roundtrip_raw = [
        ("empty",   encode(""),        '""'),
        ("ascii",   encode("hello"),   '"hello"'),
        ("unicode", encode("café"),    '"café"'),
    ]
    null_wire = bytes([0xFF])
    invalid_utf8 = bytes([0x03, 0xFF, 0xFE, 0xFD])  # length=3, invalid UTF-8

    lines = [f"    ({fmt_bytes(wire)}, {s})," for _, wire, s in roundtrip_raw]
    rt = "pub static ROUNDTRIP: &[(&[u8], &str)] = &[\n" + "\n".join(lines) + "\n];\n"

    return assemble(
        rt,
        fmt_bytes_list("NULL_WIRE", [null_wire]),
        "/// Must return Err(ZclError::InvalidUtf8).\n"
        + fmt_bytes_list("INVALID_UTF8", [invalid_utf8]),
    )


def gen_short_octet_string() -> str:
    def encode(b: bytes) -> bytes:
        return bytes([len(b)]) + b

    roundtrip_raw = [
        (encode(b""),        "b\"\""),
        (encode(b"\x00"),    "b\"\\x00\""),
        (encode(b"\xDE\xAD\xBE\xEF"), "b\"\\xDE\\xAD\\xBE\\xEF\""),
    ]
    null_wire = bytes([0xFF])

    lines = [f"    ({fmt_bytes(wire)}, {s})," for wire, s in roundtrip_raw]
    rt = "pub static ROUNDTRIP: &[(&[u8], &[u8])] = &[\n" + "\n".join(lines) + "\n];\n"

    return assemble(
        rt,
        fmt_bytes_list("NULL_WIRE", [null_wire]),
    )


def gen_array_u16() -> str:
    """
    Wire format: [element_type: u8 (0x21), count: u16 LE, elements...]
    Null sentinel: count = 0xFFFF.
    """
    def encode_array(element_type: int, elements: list[int], elem_size: int) -> bytes:
        count = len(elements)
        payload = b"".join(struct.pack("<H", e) for e in elements)
        return bytes([element_type]) + struct.pack("<H", count) + payload

    empty    = encode_array(0x21, [], 2)
    one_elem = encode_array(0x21, [1], 2)
    multi    = encode_array(0x21, [1, 2, 3], 2)
    null_wire = bytes([0x21, 0xFF, 0xFF])  # element_type=u16, count=null sentinel

    return assemble(
        "/// (wire, expected element count)\n"
        "pub static ROUNDTRIP_COUNTS: &[(&[u8], usize)] = &[\n"
        f"    ({fmt_bytes(empty)}, 0),\n"
        f"    ({fmt_bytes(one_elem)}, 1),\n"
        f"    ({fmt_bytes(multi)}, 3),\n"
        "];\n",
        fmt_bytes_list("NULL_WIRE", [null_wire]),
        "/// Must return Err(ZclError::TypeIdMismatch) — element_type byte is wrong.\n"
        + fmt_bytes_list(
            "TYPE_MISMATCH",
            [bytes([0x20, 0x01, 0x00, 0x00, 0x00])]  # says u8 but encoded as u16
        ),
    )


def gen_set_u8() -> str:
    """Set requires unique elements; duplicates must return Err(ZclError::InvalidValue)."""
    def encode_set(elements: list[int]) -> bytes:
        count = len(elements)
        payload = bytes(elements)
        return bytes([0x20]) + struct.pack("<H", count) + payload

    unique_two  = encode_set([0x01, 0x02])
    unique_three = encode_set([0x0A, 0x0B, 0x0C])
    dup         = encode_set([0x01, 0x01])  # duplicate → must fail

    return assemble(
        "pub static VALID: &[&[u8]] = &[\n"
        f"    {fmt_bytes(unique_two)},\n"
        f"    {fmt_bytes(unique_three)},\n"
        "];\n",
        "/// Must return Err(ZclError::InvalidValue) — duplicate elements.\n"
        + fmt_bytes_list("DUPLICATE_ELEMENT", [dup]),
    )


# ---------------------------------------------------------------------------
# Collection matrix generators (Array, Bag, Set, Struct)
# ---------------------------------------------------------------------------

def _encode_coll(elem_type_id: int, payload: bytes, count: int) -> bytes:
    """Wire: [elem_type_id, count_lo, count_hi, payload...]"""
    return bytes([elem_type_id]) + struct.pack("<H", count) + payload


def _encode_coll_null(elem_type_id: int) -> bytes:
    return bytes([elem_type_id, 0xFF, 0xFF])


def fmt_roundtrip_collection(cases: list[tuple[bytes, list]], rust_elem_type: str, rust_suffix: str) -> str:
    def fmt_elems(elems: list) -> str:
        if not elems:
            return "&[]"
        if rust_elem_type == "bool":
            parts = ["true" if e else "false" for e in elems]
        else:
            parts = [f"{e}{rust_suffix}" for e in elems]
        return "&[" + ", ".join(parts) + "]"

    lines = [f"    ({fmt_bytes(wire)}, {fmt_elems(elems)})," for wire, elems in cases]
    return (
        f"pub static ROUNDTRIP: &[(&[u8], &[{rust_elem_type}])] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )


def gen_collection(
    elem_type_id: int,
    elem_size: int,
    serialize_fn,
    rust_elem_type: str,
    rust_suffix: str,
    sample_sets: list[list],
    wrong_elem_type_id: int,
) -> str:
    """
    Generate collection vectors: ROUNDTRIP + NULL_WIRE + TYPE_MISMATCH.
    Works for both Array and Bag (same wire format — only the schema kind differs).
    """
    roundtrip_cases = []
    for elems in sample_sets:
        payload = b"".join(serialize_fn(e) for e in elems)
        wire = _encode_coll(elem_type_id, payload, len(elems))
        roundtrip_cases.append((wire, elems))

    null_wire = _encode_coll_null(elem_type_id)
    # type mismatch: wrong element_type_id byte, one element of `elem_size` zeros
    mismatch_wire = _encode_coll(wrong_elem_type_id, bytes(elem_size), 1)

    return assemble(
        fmt_roundtrip_collection(roundtrip_cases, rust_elem_type, rust_suffix),
        fmt_bytes_list("NULL_WIRE", [null_wire]),
        "/// Must return Err(ZclError::TypeIdMismatch) — element_type byte is wrong.\n"
        + fmt_bytes_list("TYPE_MISMATCH", [mismatch_wire]),
    )


def gen_collection_set(
    elem_type_id: int,
    serialize_fn,
    rust_elem_type: str,
    rust_suffix: str,
    unique_sample_sets: list[list],
    duplicate_sample: list,
) -> str:
    """Generate set vectors: VALID (with element values) + DUPLICATE."""
    def fmt_elems(elems: list) -> str:
        if not elems:
            return "&[]"
        if rust_elem_type == "bool":
            parts = ["true" if e else "false" for e in elems]
        else:
            parts = [f"{e}{rust_suffix}" for e in elems]
        return "&[" + ", ".join(parts) + "]"

    valid_cases = []
    for elems in unique_sample_sets:
        payload = b"".join(serialize_fn(e) for e in elems)
        wire = _encode_coll(elem_type_id, payload, len(elems))
        valid_cases.append((wire, elems))

    dup_payload = b"".join(serialize_fn(e) for e in duplicate_sample)
    dup_wire = _encode_coll(elem_type_id, dup_payload, len(duplicate_sample))

    lines = [f"    ({fmt_bytes(wire)}, {fmt_elems(elems)})," for wire, elems in valid_cases]
    valid_static = (
        f"pub static VALID: &[(&[u8], &[{rust_elem_type}])] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )

    return assemble(
        valid_static,
        "/// Must return Err(ZclError::InvalidValue) — duplicate elements.\n"
        + fmt_bytes_list("DUPLICATE", [dup_wire]),
    )


def gen_collection_struct_pair() -> str:
    """
    Typed struct with two fields: u8 + u16.
    Wire: [field_count=2 LE, 0x20 (Uint8 type), u8_val, 0x21 (Uint16 type), u16_val LE]
    Null sentinel: field_count = 0xFFFF → [0xFF, 0xFF]
    """
    def encode_pair(u8_val: int, u16_val: int) -> bytes:
        return struct.pack("<H", 2) + bytes([0x20, u8_val, 0x21]) + struct.pack("<H", u16_val)

    cases = [
        (0x42, 0x1234),
        (0x00, 0x0000),
        (0xFE, 0xFFFE),  # max non-sentinel values for u8 and u16
    ]
    lines = [
        f"    ({fmt_bytes(encode_pair(a, b))}, ({a}u8, {b}u16)),"
        for a, b in cases
    ]
    rt = (
        "pub static ROUNDTRIP: &[(&[u8], (u8, u16))] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )
    null_wire = struct.pack("<H", 0xFFFF)  # field_count = null sentinel
    return assemble(rt, fmt_bytes_list("NULL_WIRE", [null_wire]))


def gen_nested_array_u8() -> str:
    """
    ArrayOf<ArrayOf<u8>>: outer array where each element is itself an ArrayOf<u8>.
    Outer wire: [0x48 (Array elem_type), count_lo, count_hi, inner_arrays...]
    Each inner array: [0x20 (u8 elem_type), count_lo, count_hi, u8_bytes...]
    Null sentinel: outer count = 0xFFFF → [0x48, 0xFF, 0xFF]
    """
    ARRAY_TYPE_ID = 0x48
    U8_TYPE_ID = 0x20

    def encode_inner(elems: list) -> bytes:
        return _encode_coll(U8_TYPE_ID, bytes(elems), len(elems))

    sample_sets = [[], [[]], [[1, 2], [3]]]

    lines = []
    for inner_lists in sample_sets:
        outer_payload = b"".join(encode_inner(lst) for lst in inner_lists)
        outer_wire = _encode_coll(ARRAY_TYPE_ID, outer_payload, len(inner_lists))
        inner_wire_strs = [fmt_bytes(encode_inner(lst)) for lst in inner_lists]
        inner_static = "&[" + ", ".join(inner_wire_strs) + "]" if inner_wire_strs else "&[]"
        lines.append(f"    ({fmt_bytes(outer_wire)}, {inner_static}),")

    rt = (
        "/// (outer_wire, inner_element_wires) — each inner wire is a valid ArrayOf<u8> encoding.\n"
        "pub static ROUNDTRIP: &[(&[u8], &[&[u8]])] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )
    null_wire = _encode_coll_null(ARRAY_TYPE_ID)
    mismatch_wire = _encode_coll(U8_TYPE_ID, bytes(1), 1)
    return assemble(
        rt,
        fmt_bytes_list("NULL_WIRE", [null_wire]),
        "/// Must return Err(ZclError::TypeIdMismatch) — element_type byte is wrong.\n"
        + fmt_bytes_list("TYPE_MISMATCH", [mismatch_wire]),
    )


def gen_array_of_struct_pair() -> str:
    """
    ArrayOf<StructOf<PairStruct>>: array where each element is a (u8, u16) struct.
    Outer wire: [0x4C (Structure elem_type), count_lo, count_hi, structs...]
    Each struct: [field_count=2 LE, 0x20 (u8 type), u8_val, 0x21 (u16 type), u16_val LE]
    Null sentinel: outer count = 0xFFFF → [0x4C, 0xFF, 0xFF]
    """
    STRUCT_TYPE_ID = 0x4C

    def encode_pair_struct(u8_val: int, u16_val: int) -> bytes:
        return struct.pack("<H", 2) + bytes([0x20, u8_val, 0x21]) + struct.pack("<H", u16_val)

    sample_sets = [
        [],
        [(0x42, 0x1234)],
        [(0, 0), (0x42, 0x1234)],
    ]

    lines = []
    for pairs in sample_sets:
        payload = b"".join(encode_pair_struct(u8v, u16v) for u8v, u16v in pairs)
        outer_wire = _encode_coll(STRUCT_TYPE_ID, payload, len(pairs))
        rust_elems = "&[" + ", ".join(f"({u8v}u8, {u16v}u16)" for u8v, u16v in pairs) + "]"
        lines.append(f"    ({fmt_bytes(outer_wire)}, {rust_elems}),")

    rt = (
        "pub static ROUNDTRIP: &[(&[u8], &[(u8, u16)])] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )
    null_wire = _encode_coll_null(STRUCT_TYPE_ID)
    mismatch_wire = _encode_coll(0x20, bytes(1), 1)
    return assemble(
        rt,
        fmt_bytes_list("NULL_WIRE", [null_wire]),
        "/// Must return Err(ZclError::TypeIdMismatch) — element_type byte is wrong.\n"
        + fmt_bytes_list("TYPE_MISMATCH", [mismatch_wire]),
    )


def gen_struct_with_array() -> str:
    """
    Struct with fields (u8, ArrayOf<u8>).
    Wire: [field_count=2 LE, 0x20 (u8 type), u8_val, 0x48 (Array type), array_encoding...]
    Array encoding: [0x20 (u8 elem_type), count_lo, count_hi, u8_bytes...]
    Null sentinel: field_count = 0xFFFF → [0xFF, 0xFF]
    """
    U8_TYPE_ID = 0x20
    ARRAY_TYPE_ID = 0x48

    def encode_struct(u8_val: int, arr_elems: list) -> bytes:
        arr_enc = _encode_coll(U8_TYPE_ID, bytes(arr_elems), len(arr_elems))
        return struct.pack("<H", 2) + bytes([U8_TYPE_ID, u8_val, ARRAY_TYPE_ID]) + arr_enc

    samples = [(0, []), (42, [1, 2, 3]), (254, [10, 20])]

    lines = []
    for u8_val, arr_elems in samples:
        wire = encode_struct(u8_val, arr_elems)
        rust_arr = ", ".join(f"{e}u8" for e in arr_elems)
        lines.append(f"    ({fmt_bytes(wire)}, ({u8_val}u8, &[{rust_arr}])),")

    rt = (
        "/// (wire, (u8_field, array_field_elements))\n"
        "pub static ROUNDTRIP: &[(&[u8], (u8, &[u8]))] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )
    null_wire = bytes([0xFF, 0xFF])
    return assemble(rt, fmt_bytes_list("NULL_WIRE", [null_wire]))


GENERATORS: dict[str, tuple[str, callable]] = {
    # (output filename, generator function)
    "u8":                ("u8.rs",                 lambda: gen_uint(t.uint8_t,  "u8",  8)),
    "u16":               ("u16.rs",                lambda: gen_uint(t.uint16_t, "u16", 16)),
    "u32":               ("u32.rs",                lambda: gen_uint(t.uint32_t, "u32", 32)),
    "u64":               ("u64.rs",                lambda: gen_uint(t.uint64_t, "u64", 64)),
    "i8":                ("i8.rs",                 lambda: gen_sint(t.int8s,    "i8",  8)),
    "i16":               ("i16.rs",                lambda: gen_sint(t.int16s,   "i16", 16)),
    "i32":               ("i32.rs",                lambda: gen_sint(t.int32s,   "i32", 32)),
    "i64":               ("i64.rs",                lambda: gen_sint(t.int64s,   "i64", 64)),
    "bool":              ("bool.rs",               gen_bool),
    "f32":               ("f32.rs",                gen_f32),
    "f64":               ("f64.rs",                gen_f64),
    "bitmap8":           ("bitmap8.rs",            lambda: gen_bitmap(t.bitmap8,  "Bitmap8",  "u8",  8)),
    "bitmap16":          ("bitmap16.rs",           lambda: gen_bitmap(t.bitmap16, "Bitmap16", "u16", 16)),
    "bitmap32":          ("bitmap32.rs",           lambda: gen_bitmap(t.bitmap32, "Bitmap32", "u32", 32)),
    "bitmap64":          ("bitmap64.rs",           lambda: gen_bitmap(t.bitmap64, "Bitmap64", "u64", 64)),
    "enum8":             ("enum8.rs",              gen_enum8),
    "enum16":            ("enum16.rs",             gen_enum16),
    "short_text":        ("short_text.rs",         gen_short_text),
    "short_octet_string":("short_octet_string.rs", gen_short_octet_string),
    # Collection matrix — Array × element type
    "coll_array_u8":   ("collections/array_u8.rs",  lambda: gen_collection(
        0x20, 1, lambda v: t.uint8_t(v).serialize(), "u8", "u8",
        [[], [42], [1, 100, 0xFE]], 0x21)),
    "coll_array_u16":  ("collections/array_u16.rs", lambda: gen_collection(
        0x21, 2, lambda v: t.uint16_t(v).serialize(), "u16", "u16",
        [[], [1], [1, 2, 3]], 0x20)),
    "coll_array_i16":  ("collections/array_i16.rs", lambda: gen_collection(
        0x29, 2, lambda v: t.int16s(v).serialize(), "i16", "i16",
        [[], [-1], [0, 100, -100]], 0x20)),
    "coll_array_bool": ("collections/array_bool.rs", lambda: gen_collection(
        0x10, 1, lambda v: t.Bool(v).serialize(), "bool", "",
        [[], [True], [False, True, False]], 0x20)),
    # Collection matrix — Bag × element type (same wire format, different schema kind)
    "coll_bag_u8":     ("collections/bag_u8.rs",  lambda: gen_collection(
        0x20, 1, lambda v: t.uint8_t(v).serialize(), "u8", "u8",
        [[], [42], [1, 100, 0xFE]], 0x21)),
    "coll_bag_u16":    ("collections/bag_u16.rs", lambda: gen_collection(
        0x21, 2, lambda v: t.uint16_t(v).serialize(), "u16", "u16",
        [[], [1], [1, 2, 3]], 0x20)),
    # Collection matrix — Set × element type (uniqueness enforced)
    "coll_set_u8":     ("collections/set_u8.rs",  lambda: gen_collection_set(
        0x20, lambda v: t.uint8_t(v).serialize(), "u8", "u8",
        [[1, 2], [10, 11, 12]], [1, 1])),
    "coll_set_u16":    ("collections/set_u16.rs", lambda: gen_collection_set(
        0x21, lambda v: t.uint16_t(v).serialize(), "u16", "u16",
        [[1, 2], [10, 20, 30]], [1, 1])),
    # Struct: (u8, u16) pair with StructEncoder/StructDecoder
    "coll_struct_pair": ("collections/struct_pair.rs", gen_collection_struct_pair),
    # Nesting: ArrayOf<ArrayOf<u8>>, ArrayOf<StructOf<PairStruct>>, struct with array field
    "coll_nested_array_u8":      ("collections/array_of_array_u8.rs",  gen_nested_array_u8),
    "coll_array_of_struct_pair": ("collections/array_of_struct_pair.rs", gen_array_of_struct_pair),
    "coll_struct_with_array":    ("collections/struct_with_array.rs",   gen_struct_with_array),
}

def write_or_check(path: Path, content: str, check: bool) -> bool:
    """Return True if content matches what is on disk (or was written). False if drift."""
    if check:
        existing = path.read_text() if path.exists() else ""
        if existing == content:
            return True
        diff = difflib.unified_diff(
            existing.splitlines(keepends=True),
            content.splitlines(keepends=True),
            fromfile=str(path),
            tofile="generated",
        )
        sys.stderr.write("".join(diff))
        return False
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True, type=Path, help="Output directory")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Diff against existing files; exit 1 if any differ (no writes)",
    )
    args = parser.parse_args()

    ok = True
    for name, (filename, gen_fn) in GENERATORS.items():
        try:
            content = gen_fn()
        except Exception as exc:
            print(f"  ERROR {name}: {exc}", file=sys.stderr)
            ok = False
            continue

        dest = args.out / filename
        if write_or_check(dest, content, args.check):
            if not args.check:
                print(f"  wrote {dest}")
        else:
            print(f"  DRIFT {dest}", file=sys.stderr)
            ok = False

    if not ok and args.check:
        print(
            "\nVectors out of date — run `cargo xtask generate-vectors` to refresh.",
            file=sys.stderr,
        )
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
