# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "zigpy==1.4.1",
# ]
# ///
"""
ZCL test vector generator.

Uses zigpy as the reference implementation to produce byte-exact
encodings for each ZCL type supported by zigbee-cluster-library.

Run via xtask (preferred):
    cargo xtask generate-vectors   # write to zigbee-cluster-library/tests/vectors/
    cargo xtask check-vectors      # diff against committed vectors; exit 1 on drift

Or directly:
    uv run scripts/gen_vectors.py --out zigbee-cluster-library/tests/vectors/
    uv run scripts/gen_vectors.py --out /tmp/check --check
"""

import argparse
import difflib
import importlib.metadata
import struct
import sys
from pathlib import Path
from typing import Any

import zigpy.types as t
import zigpy.zcl.clusters.general as zcl_general
import zigpy.zcl.clusters.homeautomation as zcl_homeautomation
import zigpy.zcl.clusters.measurement as zcl_measurement
import zigpy.zcl.clusters.hvac as zcl_hvac

ZIGPY_VERSION = importlib.metadata.version("zigpy")

HEADER = f"""\
// Code generated by scripts/gen_vectors.py using zigpy {ZIGPY_VERSION}. DO NOT EDIT.
// Run `cargo xtask generate-vectors` to refresh.
"""

def fmt_bytes(b: bytes) -> str:
    return "&[" + ", ".join(f"0x{byte:02X}" for byte in b) + "]"


def fmt_roundtrip_scalar(pairs: list[tuple[bytes, str]], rust_type: str) -> str:
    lines = [f"    ({fmt_bytes(wire)}, {val}{rust_type})," for wire, val in pairs]
    return (
        f"pub static ROUNDTRIP: &[(&[u8], {rust_type})] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )


def fmt_roundtrip_bool(pairs: list[tuple[bytes, str]]) -> str:
    lines = [f"    ({fmt_bytes(wire)}, {val})," for wire, val in pairs]
    return (
        "pub static ROUNDTRIP: &[(&[u8], bool)] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )


def fmt_bytes_list(name: str, items: list[bytes]) -> str:
    lines = [f"    {fmt_bytes(b)}," for b in items]
    return f"pub static {name}: &[&[u8]] = &[\n" + "\n".join(lines) + "\n];\n"


def fmt_roundtrip_bits(pairs: list[tuple[bytes, str]], rust_type: str, inner: str) -> str:
    """For bitmaps: store as (wire, u64 raw value) since the Rust type is a newtype."""
    lines = [f"    ({fmt_bytes(wire)}, {val}{inner})," for wire, val in pairs]
    return (
        f"pub static ROUNDTRIP_RAW: &[(&[u8], {inner})] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )


def assemble(*sections: str) -> str:
    return HEADER + "\n" + "\n".join(s for s in sections if s)


def gen_uint(zigpy_type, rust_type: str, bits: int) -> str:
    max_valid = (1 << bits) - 2  # one below null sentinel
    null_val = (1 << bits) - 1

    values = [0, 1, max_valid // 2 + 1, max_valid]
    roundtrip = [
        (zigpy_type(v).serialize(), str(v))
        for v in values
    ]
    null_wire = zigpy_type(null_val).serialize()

    return assemble(
        fmt_roundtrip_scalar(roundtrip, rust_type),
        fmt_bytes_list("NULL_WIRE", [null_wire]),
    )


def gen_sint(zigpy_type, rust_type: str, bits: int) -> str:
    null_val = -(1 << (bits - 1))   # e.g. -128 for i8
    max_val = (1 << (bits - 1)) - 1  # e.g. 127

    values = [0, 1, -1, max_val, null_val + 1]  # null+1 = one above sentinel
    roundtrip = [
        (zigpy_type(v).serialize(), str(v))
        for v in values
    ]
    null_wire = zigpy_type(null_val).serialize()

    return assemble(
        fmt_roundtrip_scalar(roundtrip, rust_type),
        fmt_bytes_list("NULL_WIRE", [null_wire]),
    )


def gen_bool() -> str:
    # ZCL bool: 0x00 = false, 0x01 = true, 0xFF = null sentinel.
    roundtrip = [
        (t.Bool(False).serialize(), "false"),
        (t.Bool(True).serialize(), "true"),
    ]
    # Values that must return ZclError::InvalidValue, not NullSentinel.
    invalid = [bytes([0x02]), bytes([0xFE])]
    null_wire = bytes([0xFF])

    return assemble(
        fmt_roundtrip_bool(roundtrip),
        fmt_bytes_list("NULL_WIRE", [null_wire]),
        "/// These must return Err(ZclError::InvalidValue), not NullSentinel.\n"
        + fmt_bytes_list("INVALID_VALUE", invalid),
    )


def gen_f32() -> str:
    # Roundtrip stored as raw bit patterns (u32) to avoid float equality issues.
    vals: list[tuple[float, str]] = [
        (0.0, "0"),
        (1.0, str(struct.unpack('<I', struct.pack('<f', 1.0))[0])),
        (-1.0, str(struct.unpack('<I', struct.pack('<f', -1.0))[0])),
        (1.5, str(struct.unpack('<I', struct.pack('<f', 1.5))[0])),
    ]
    roundtrip_raw = [
        (t.Single(v).serialize(), bits)
        for v, bits in vals
    ]
    # ZCL Single Precision null = any NaN; the canonical zigpy NaN
    null_wire = t.Single(float("nan")).serialize()

    lines = [f"    ({fmt_bytes(wire)}, {bits}u32)," for wire, bits in roundtrip_raw]
    roundtrip_section = (
        "/// Compare decoded f32 bits via f32::to_bits() to avoid NaN != NaN.\n"
        "pub static ROUNDTRIP_BITS: &[(&[u8], u32)] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )
    return assemble(
        roundtrip_section,
        fmt_bytes_list("NULL_WIRE", [null_wire]),
    )


def gen_f64() -> str:
    vals: list[tuple[float, str]] = [
        (0.0, "0"),
        (1.0, str(struct.unpack('<Q', struct.pack('<d', 1.0))[0])),
        (-1.0, str(struct.unpack('<Q', struct.pack('<d', -1.0))[0])),
        (1.5, str(struct.unpack('<Q', struct.pack('<d', 1.5))[0])),
    ]
    roundtrip_raw = [
        (t.Double(v).serialize(), bits)
        for v, bits in vals
    ]
    null_wire = t.Double(float("nan")).serialize()

    lines = [f"    ({fmt_bytes(wire)}, {bits}u64)," for wire, bits in roundtrip_raw]
    roundtrip_section = (
        "/// Compare decoded f64 bits via f64::to_bits() to avoid NaN != NaN.\n"
        "pub static ROUNDTRIP_BITS: &[(&[u8], u64)] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )
    return assemble(
        roundtrip_section,
        fmt_bytes_list("NULL_WIRE", [null_wire]),
    )


def gen_bitmap(zigpy_type, rust_type: str, inner: str, bits: int) -> str:
    all_ones = (1 << bits) - 1
    values = [0, 1, 0b10101010, all_ones]
    roundtrip = [
        (zigpy_type(v).serialize(), str(v))
        for v in values
        if v <= all_ones
    ]
    # Bitmaps have no null sentinel; ALL_PATTERNS_VALID = true.
    return assemble(fmt_roundtrip_bits(roundtrip, rust_type, inner))


def gen_enum8() -> str:
    # Enum decode is user-driven (the Rust callback decides valid discriminants).
    # Vectors here test that the schema passes the raw byte through correctly;
    # application-level validation is tested in cluster-specific tests.
    roundtrip = [
        (t.enum8(v).serialize(), str(v))
        for v in [0x00, 0x01, 0x42, 0xFE]
    ]
    null_wire = t.enum8(0xFF).serialize()
    return assemble(
        fmt_roundtrip_scalar(roundtrip, "u8"),
        fmt_bytes_list("NULL_WIRE", [null_wire]),
    )


def gen_enum16() -> str:
    roundtrip = [
        (t.enum16(v).serialize(), str(v))
        for v in [0x0000, 0x0001, 0x0100, 0xFFFE]
    ]
    null_wire = t.enum16(0xFFFF).serialize()
    return assemble(
        fmt_roundtrip_scalar(roundtrip, "u16"),
        fmt_bytes_list("NULL_WIRE", [null_wire]),
    )


def gen_short_text() -> str:
    # Wire: [len: u8, utf8 bytes...]  null sentinel: len = 0xFF
    def encode(s: str) -> bytes:
        b = s.encode("utf-8")
        return bytes([len(b)]) + b

    roundtrip_raw = [
        ("empty",   encode(""),        '""'),
        ("ascii",   encode("hello"),   '"hello"'),
        ("unicode", encode("café"),    '"café"'),
    ]
    null_wire = bytes([0xFF])
    invalid_utf8 = bytes([0x03, 0xFF, 0xFE, 0xFD])  # length=3, invalid UTF-8

    lines = [f"    ({fmt_bytes(wire)}, {s})," for _, wire, s in roundtrip_raw]
    rt = "pub static ROUNDTRIP: &[(&[u8], &str)] = &[\n" + "\n".join(lines) + "\n];\n"

    return assemble(
        rt,
        fmt_bytes_list("NULL_WIRE", [null_wire]),
        "/// Must return Err(ZclError::InvalidUtf8).\n"
        + fmt_bytes_list("INVALID_UTF8", [invalid_utf8]),
    )


def gen_short_octet_string() -> str:
    def encode(b: bytes) -> bytes:
        return bytes([len(b)]) + b

    roundtrip_raw = [
        (encode(b""),        "b\"\""),
        (encode(b"\x00"),    "b\"\\x00\""),
        (encode(b"\xDE\xAD\xBE\xEF"), "b\"\\xDE\\xAD\\xBE\\xEF\""),
    ]
    null_wire = bytes([0xFF])

    lines = [f"    ({fmt_bytes(wire)}, {s})," for wire, s in roundtrip_raw]
    rt = "pub static ROUNDTRIP: &[(&[u8], &[u8])] = &[\n" + "\n".join(lines) + "\n];\n"

    return assemble(
        rt,
        fmt_bytes_list("NULL_WIRE", [null_wire]),
    )


def gen_array_u16() -> str:
    """
    Wire format: [element_type: u8 (0x21), count: u16 LE, elements...]
    Null sentinel: count = 0xFFFF.
    """
    def encode_array(element_type: int, elements: list[int], elem_size: int) -> bytes:
        count = len(elements)
        payload = b"".join(struct.pack("<H", e) for e in elements)
        return bytes([element_type]) + struct.pack("<H", count) + payload

    empty    = encode_array(0x21, [], 2)
    one_elem = encode_array(0x21, [1], 2)
    multi    = encode_array(0x21, [1, 2, 3], 2)
    null_wire = bytes([0x21, 0xFF, 0xFF])  # element_type=u16, count=null sentinel

    return assemble(
        "/// (wire, expected element count)\n"
        "pub static ROUNDTRIP_COUNTS: &[(&[u8], usize)] = &[\n"
        f"    ({fmt_bytes(empty)}, 0),\n"
        f"    ({fmt_bytes(one_elem)}, 1),\n"
        f"    ({fmt_bytes(multi)}, 3),\n"
        "];\n",
        fmt_bytes_list("NULL_WIRE", [null_wire]),
        "/// Must return Err(ZclError::TypeIdMismatch) — element_type byte is wrong.\n"
        + fmt_bytes_list(
            "TYPE_MISMATCH",
            [bytes([0x20, 0x01, 0x00, 0x00, 0x00])]  # says u8 but encoded as u16
        ),
    )


def gen_set_u8() -> str:
    """Set requires unique elements; duplicates must return Err(ZclError::InvalidValue)."""
    def encode_set(elements: list[int]) -> bytes:
        count = len(elements)
        payload = bytes(elements)
        return bytes([0x20]) + struct.pack("<H", count) + payload

    unique_two  = encode_set([0x01, 0x02])
    unique_three = encode_set([0x0A, 0x0B, 0x0C])
    dup         = encode_set([0x01, 0x01])  # duplicate → must fail

    return assemble(
        "pub static VALID: &[&[u8]] = &[\n"
        f"    {fmt_bytes(unique_two)},\n"
        f"    {fmt_bytes(unique_three)},\n"
        "];\n",
        "/// Must return Err(ZclError::InvalidValue) — duplicate elements.\n"
        + fmt_bytes_list("DUPLICATE_ELEMENT", [dup]),
    )


# ---------------------------------------------------------------------------
# Collection matrix generators (Array, Bag, Set, Struct)
# ---------------------------------------------------------------------------

def _encode_coll(elem_type_id: int, payload: bytes, count: int) -> bytes:
    """Wire: [elem_type_id, count_lo, count_hi, payload...]"""
    return bytes([elem_type_id]) + struct.pack("<H", count) + payload


def _encode_coll_null(elem_type_id: int) -> bytes:
    return bytes([elem_type_id, 0xFF, 0xFF])


def fmt_roundtrip_collection(cases: list[tuple[bytes, list]], rust_elem_type: str, rust_suffix: str) -> str:
    def fmt_elems(elems: list) -> str:
        if not elems:
            return "&[]"
        if rust_elem_type == "bool":
            parts = ["true" if e else "false" for e in elems]
        else:
            parts = [f"{e}{rust_suffix}" for e in elems]
        return "&[" + ", ".join(parts) + "]"

    lines = [f"    ({fmt_bytes(wire)}, {fmt_elems(elems)})," for wire, elems in cases]
    return (
        f"pub static ROUNDTRIP: &[(&[u8], &[{rust_elem_type}])] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )


def gen_collection(
    elem_type_id: int,
    elem_size: int,
    serialize_fn,
    rust_elem_type: str,
    rust_suffix: str,
    sample_sets: list[list],
    wrong_elem_type_id: int,
) -> str:
    """
    Generate collection vectors: ROUNDTRIP + NULL_WIRE + TYPE_MISMATCH.
    Works for both Array and Bag (same wire format — only the schema kind differs).
    """
    roundtrip_cases = []
    for elems in sample_sets:
        payload = b"".join(serialize_fn(e) for e in elems)
        wire = _encode_coll(elem_type_id, payload, len(elems))
        roundtrip_cases.append((wire, elems))

    null_wire = _encode_coll_null(elem_type_id)
    # type mismatch: wrong element_type_id byte, one element of `elem_size` zeros
    mismatch_wire = _encode_coll(wrong_elem_type_id, bytes(elem_size), 1)

    return assemble(
        fmt_roundtrip_collection(roundtrip_cases, rust_elem_type, rust_suffix),
        fmt_bytes_list("NULL_WIRE", [null_wire]),
        "/// Must return Err(ZclError::TypeIdMismatch) — element_type byte is wrong.\n"
        + fmt_bytes_list("TYPE_MISMATCH", [mismatch_wire]),
    )


def gen_collection_set(
    elem_type_id: int,
    serialize_fn,
    rust_elem_type: str,
    rust_suffix: str,
    unique_sample_sets: list[list],
    duplicate_sample: list,
) -> str:
    """Generate set vectors: VALID (with element values) + DUPLICATE."""
    def fmt_elems(elems: list) -> str:
        if not elems:
            return "&[]"
        if rust_elem_type == "bool":
            parts = ["true" if e else "false" for e in elems]
        else:
            parts = [f"{e}{rust_suffix}" for e in elems]
        return "&[" + ", ".join(parts) + "]"

    valid_cases = []
    for elems in unique_sample_sets:
        payload = b"".join(serialize_fn(e) for e in elems)
        wire = _encode_coll(elem_type_id, payload, len(elems))
        valid_cases.append((wire, elems))

    dup_payload = b"".join(serialize_fn(e) for e in duplicate_sample)
    dup_wire = _encode_coll(elem_type_id, dup_payload, len(duplicate_sample))

    lines = [f"    ({fmt_bytes(wire)}, {fmt_elems(elems)})," for wire, elems in valid_cases]
    valid_static = (
        f"pub static VALID: &[(&[u8], &[{rust_elem_type}])] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )

    return assemble(
        valid_static,
        "/// Must return Err(ZclError::InvalidValue) — duplicate elements.\n"
        + fmt_bytes_list("DUPLICATE", [dup_wire]),
    )


def gen_collection_struct_pair() -> str:
    """
    Typed struct with two fields: u8 + u16.
    Wire: [field_count=2 LE, 0x20 (Uint8 type), u8_val, 0x21 (Uint16 type), u16_val LE]
    Null sentinel: field_count = 0xFFFF → [0xFF, 0xFF]
    """
    def encode_pair(u8_val: int, u16_val: int) -> bytes:
        return struct.pack("<H", 2) + bytes([0x20, u8_val, 0x21]) + struct.pack("<H", u16_val)

    cases = [
        (0x42, 0x1234),
        (0x00, 0x0000),
        (0xFE, 0xFFFE),  # max non-sentinel values for u8 and u16
    ]
    lines = [
        f"    ({fmt_bytes(encode_pair(a, b))}, ({a}u8, {b}u16)),"
        for a, b in cases
    ]
    rt = (
        "pub static ROUNDTRIP: &[(&[u8], (u8, u16))] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )
    null_wire = struct.pack("<H", 0xFFFF)  # field_count = null sentinel
    return assemble(rt, fmt_bytes_list("NULL_WIRE", [null_wire]))


def gen_nested_array_u8() -> str:
    """
    ArrayOf<ArrayOf<u8>>: outer array where each element is itself an ArrayOf<u8>.
    Outer wire: [0x48 (Array elem_type), count_lo, count_hi, inner_arrays...]
    Each inner array: [0x20 (u8 elem_type), count_lo, count_hi, u8_bytes...]
    Null sentinel: outer count = 0xFFFF → [0x48, 0xFF, 0xFF]
    """
    ARRAY_TYPE_ID = 0x48
    U8_TYPE_ID = 0x20

    def encode_inner(elems: list) -> bytes:
        return _encode_coll(U8_TYPE_ID, bytes(elems), len(elems))

    sample_sets = [[], [[]], [[1, 2], [3]]]

    lines = []
    for inner_lists in sample_sets:
        outer_payload = b"".join(encode_inner(lst) for lst in inner_lists)
        outer_wire = _encode_coll(ARRAY_TYPE_ID, outer_payload, len(inner_lists))
        inner_wire_strs = [fmt_bytes(encode_inner(lst)) for lst in inner_lists]
        inner_static = "&[" + ", ".join(inner_wire_strs) + "]" if inner_wire_strs else "&[]"
        lines.append(f"    ({fmt_bytes(outer_wire)}, {inner_static}),")

    rt = (
        "/// (outer_wire, inner_element_wires) — each inner wire is a valid ArrayOf<u8> encoding.\n"
        "pub static ROUNDTRIP: &[(&[u8], &[&[u8]])] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )
    null_wire = _encode_coll_null(ARRAY_TYPE_ID)
    mismatch_wire = _encode_coll(U8_TYPE_ID, bytes(1), 1)
    return assemble(
        rt,
        fmt_bytes_list("NULL_WIRE", [null_wire]),
        "/// Must return Err(ZclError::TypeIdMismatch) — element_type byte is wrong.\n"
        + fmt_bytes_list("TYPE_MISMATCH", [mismatch_wire]),
    )


def gen_array_of_struct_pair() -> str:
    """
    ArrayOf<StructOf<PairStruct>>: array where each element is a (u8, u16) struct.
    Outer wire: [0x4C (Structure elem_type), count_lo, count_hi, structs...]
    Each struct: [field_count=2 LE, 0x20 (u8 type), u8_val, 0x21 (u16 type), u16_val LE]
    Null sentinel: outer count = 0xFFFF → [0x4C, 0xFF, 0xFF]
    """
    STRUCT_TYPE_ID = 0x4C

    def encode_pair_struct(u8_val: int, u16_val: int) -> bytes:
        return struct.pack("<H", 2) + bytes([0x20, u8_val, 0x21]) + struct.pack("<H", u16_val)

    sample_sets = [
        [],
        [(0x42, 0x1234)],
        [(0, 0), (0x42, 0x1234)],
    ]

    lines = []
    for pairs in sample_sets:
        payload = b"".join(encode_pair_struct(u8v, u16v) for u8v, u16v in pairs)
        outer_wire = _encode_coll(STRUCT_TYPE_ID, payload, len(pairs))
        rust_elems = "&[" + ", ".join(f"({u8v}u8, {u16v}u16)" for u8v, u16v in pairs) + "]"
        lines.append(f"    ({fmt_bytes(outer_wire)}, {rust_elems}),")

    rt = (
        "pub static ROUNDTRIP: &[(&[u8], &[(u8, u16)])] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )
    null_wire = _encode_coll_null(STRUCT_TYPE_ID)
    mismatch_wire = _encode_coll(0x20, bytes(1), 1)
    return assemble(
        rt,
        fmt_bytes_list("NULL_WIRE", [null_wire]),
        "/// Must return Err(ZclError::TypeIdMismatch) — element_type byte is wrong.\n"
        + fmt_bytes_list("TYPE_MISMATCH", [mismatch_wire]),
    )


def gen_struct_with_array() -> str:
    """
    Struct with fields (u8, ArrayOf<u8>).
    Wire: [field_count=2 LE, 0x20 (u8 type), u8_val, 0x48 (Array type), array_encoding...]
    Array encoding: [0x20 (u8 elem_type), count_lo, count_hi, u8_bytes...]
    Null sentinel: field_count = 0xFFFF → [0xFF, 0xFF]
    """
    U8_TYPE_ID = 0x20
    ARRAY_TYPE_ID = 0x48

    def encode_struct(u8_val: int, arr_elems: list) -> bytes:
        arr_enc = _encode_coll(U8_TYPE_ID, bytes(arr_elems), len(arr_elems))
        return struct.pack("<H", 2) + bytes([U8_TYPE_ID, u8_val, ARRAY_TYPE_ID]) + arr_enc

    samples = [(0, []), (42, [1, 2, 3]), (254, [10, 20])]

    lines = []
    for u8_val, arr_elems in samples:
        wire = encode_struct(u8_val, arr_elems)
        rust_arr = ", ".join(f"{e}u8" for e in arr_elems)
        lines.append(f"    ({fmt_bytes(wire)}, ({u8_val}u8, &[{rust_arr}])),")

    rt = (
        "/// (wire, (u8_field, array_field_elements))\n"
        "pub static ROUNDTRIP: &[(&[u8], (u8, &[u8]))] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )
    null_wire = bytes([0xFF, 0xFF])
    return assemble(rt, fmt_bytes_list("NULL_WIRE", [null_wire]))


# ---------------------------------------------------------------------------
# Cluster vector helpers
# ---------------------------------------------------------------------------

class _FakeEndpoint:
    """Minimal stub so zigpy cluster attribute lookups work without a live device."""
    def __init__(self):
        self.device = None


def _cluster(cls):
    """Instantiate a zigpy cluster without a real endpoint."""
    try:
        return cls(endpoint=None, is_server=True)
    except Exception:
        return cls(_FakeEndpoint(), is_server=True)


def zcl_frame(frame_control: int, seq: int, cmd_id: int, payload: bytes) -> bytes:
    """Build a minimal 3-byte ZCL header + payload.

    Common frame_control values:
      0x00  global, client→server (requests)
      0x01  cluster-specific, client→server (commands)
      0x18  global, server→client (responses)
      0x19  cluster-specific, server→client
    """
    return bytes([frame_control, seq, cmd_id]) + payload


def read_attrs_request(attr_ids: list[int], seq: int = 1) -> bytes:
    """ZCL ReadAttributes request frame."""
    payload = b"".join(struct.pack("<H", a) for a in attr_ids)
    return zcl_frame(0x00, seq, 0x00, payload)


def read_attrs_response(cluster_cls, attr_values: dict[int, Any], seq: int = 1) -> bytes:
    """ZCL ReadAttributesResponse frame built from zigpy cluster schema.

    attr_values maps attribute_id → python value.  zigpy resolves the ZCL
    type tag and serializes the value; we wrap it in a ReadAttributeRecord.
    """
    cluster = _cluster(cluster_cls)
    records = b""
    for attr_id, value in attr_values.items():
        attr_def = cluster.attributes[attr_id]
        zcl_type = attr_def.type
        type_id_byte = int(attr_def.zcl_type)
        encoded_value = zcl_type(value).serialize()
        # ReadAttributeRecord: [attr_id u16 LE, status u8, type_id u8, value...]
        records += struct.pack("<HB", attr_id, 0x00) + bytes([type_id_byte]) + encoded_value
    return zcl_frame(0x18, seq, 0x01, records)


def write_attrs_request(cluster_cls, writes: dict[int, Any], seq: int = 1) -> bytes:
    """ZCL WriteAttributes request frame."""
    cluster = _cluster(cluster_cls)
    records = b""
    for attr_id, value in writes.items():
        attr_def = cluster.attributes[attr_id]
        zcl_type = attr_def.type
        type_id_byte = int(attr_def.zcl_type)
        encoded_value = zcl_type(value).serialize()
        # WriteAttributeRecord: [attr_id u16 LE, type_id u8, value...]
        records += struct.pack("<H", attr_id) + bytes([type_id_byte]) + encoded_value
    return zcl_frame(0x00, seq, 0x02, records)


def write_attrs_response_success(seq: int = 1) -> bytes:
    """ZCL WriteAttributesResponse with a single global Success status."""
    return zcl_frame(0x18, seq, 0x04, bytes([0x00]))


def write_attrs_response_error(attr_id: int, status: int, seq: int = 1) -> bytes:
    """ZCL WriteAttributesResponse with a per-attribute error record."""
    # [status u8, attr_id u16 LE]
    payload = bytes([status]) + struct.pack("<H", attr_id)
    return zcl_frame(0x18, seq, 0x04, payload)


def cluster_cmd_request(cmd_id: int, payload: bytes, seq: int = 1) -> bytes:
    """ZCL cluster-specific command request frame (client→server)."""
    return zcl_frame(0x01, seq, cmd_id, payload)


def default_response(cmd_id: int, status: int, seq: int = 1) -> bytes:
    """ZCL DefaultResponse frame (server→client)."""
    return zcl_frame(0x18, seq, 0x0B, bytes([cmd_id, status]))


def fmt_request_response_pairs(name: str, pairs: list[tuple[bytes, bytes]]) -> str:
    lines = [f"    ({fmt_bytes(req)}, {fmt_bytes(resp)})," for req, resp in pairs]
    return (
        f"pub static {name}: &[(&[u8], &[u8])] = &[\n"
        + "\n".join(lines)
        + "\n];\n"
    )


def discover_attrs_request(start_attr_id: int = 0x0000, max_count: int = 0xFF, seq: int = 1) -> bytes:
    """ZCL DiscoverAttributes request frame (cmd 0x0C)."""
    return zcl_frame(0x00, seq, 0x0C, struct.pack("<HB", start_attr_id, max_count))


def discover_attrs_response(attrs: list[tuple[int, int]], seq: int = 1) -> bytes:
    """ZCL DiscoverAttributesResponse frame (cmd 0x0D).

    attrs: list of (attr_id, type_id_byte) pairs, sorted ascending by attr_id.
    Type IDs mirror our Rust TypeId enum: Boolean=0x10, Bitmap8=0x18, Bitmap32=0x1B,
    Uint8=0x20, Uint16=0x21, Int8=0x28, Int16=0x29, Enum8=0x30, CharacterString=0x42.
    Built from the Rust attribute_list() so vectors are byte-exact against our impl.
    """
    records = b"".join(struct.pack("<HB", attr_id, type_id) for attr_id, type_id in attrs)
    return zcl_frame(0x18, seq, 0x0D, bytes([0x01]) + records)  # 0x01 = discovery_complete


# Attr lists mirroring each cluster's attribute_list() in Rust.
# Must be kept in sync with the Rust implementations.
_CLUSTER_ATTRS: dict[str, list[tuple[int, int]]] = {
    # (attr_id, type_id_byte) — sorted ascending by attr_id
    "on_off":        [(0x0000, 0x10), (0xFFFD, 0x21), (0x4000, 0x10),
                      (0x4001, 0x21), (0x4002, 0x21)],
    "level_control": [(0x0000, 0x20), (0x0001, 0x21), (0x0002, 0x20),
                      (0x0003, 0x20), (0x000F, 0x18), (0xFFFD, 0x21)],
    "basic":         [(0x0000, 0x20), (0x0004, 0x42), (0x0005, 0x42),
                      (0x0007, 0x30), (0x0012, 0x10), (0xFFFD, 0x21)],
    "temperature":   [(0x0000, 0x29), (0x0001, 0x29), (0x0002, 0x29),
                      (0x0003, 0x21), (0xFFFD, 0x21)],
    "humidity":      [(0x0000, 0x21), (0x0001, 0x21), (0x0002, 0x21),
                      (0x0003, 0x21), (0xFFFD, 0x21)],
    "pressure":      [(0x0000, 0x29), (0x0001, 0x29), (0x0002, 0x29),
                      (0x0003, 0x21), (0xFFFD, 0x21)],
    "flow":          [(0x0000, 0x21), (0x0001, 0x21), (0x0002, 0x21),
                      (0x0003, 0x21), (0xFFFD, 0x21)],
    "illuminance":   [(0x0000, 0x21), (0x0001, 0x21), (0x0002, 0x21),
                      (0x0003, 0x21), (0x0004, 0x30), (0xFFFD, 0x21)],
    "occupancy":     [(0x0000, 0x18), (0x0001, 0x30), (0x0002, 0x18),
                      (0xFFFD, 0x21)],
    "electrical":    [(0x0000, 0x1B), (0x0505, 0x21), (0x0508, 0x21),
                      (0x050B, 0x29), (0x0510, 0x28), (0xFFFD, 0x21)],
    "thermostat":    [(0x0000, 0x29), (0x0011, 0x29), (0x0012, 0x29),
                      (0x001B, 0x30), (0x001C, 0x30), (0xFFFD, 0x21)],
}


def _discover_cases(cluster_key: str, seq: int = 1) -> list[tuple[bytes, bytes]]:
    attrs = _CLUSTER_ATTRS[cluster_key]
    return [(discover_attrs_request(seq=seq), discover_attrs_response(attrs, seq=seq))]


# ---------------------------------------------------------------------------
# Cluster generators
# ---------------------------------------------------------------------------

def gen_cluster_on_off() -> str:
    SEQ = 1
    # ReadAttributes: read attr 0x0000 (OnOff) with on_off=false, then on_off=true
    read_pairs = [
        (
            read_attrs_request([0x0000], SEQ),
            read_attrs_response(zcl_general.OnOff, {0x0000: False}, SEQ),
        ),
        (
            read_attrs_request([0x0000], SEQ),
            read_attrs_response(zcl_general.OnOff, {0x0000: True}, SEQ),
        ),
    ]
    # Cluster-specific commands: Off=0x00, On=0x01, Toggle=0x02
    cmd_pairs = [
        (cluster_cmd_request(cmd_id, b"", SEQ), default_response(cmd_id, 0x00, SEQ))
        for cmd_id in [0x00, 0x01, 0x02]
    ]
    write_pairs = [
        (write_attrs_request(zcl_general.OnOff, {0x0000: False}, SEQ),
         write_attrs_response_error(0x0000, 0x88, SEQ)),
    ]
    return assemble(
        fmt_request_response_pairs("READ_CASES", read_pairs),
        fmt_request_response_pairs("COMMAND_CASES", cmd_pairs),
        fmt_request_response_pairs("WRITE_CASES", write_pairs),
        fmt_request_response_pairs("DISCOVER_CASES", _discover_cases("on_off", SEQ)),
    )


def _gen_cluster_measurement(
    cluster_cls,
    measured_attr_id: int,
    values: list[int],
    cluster_key: str,
    extra_read_attrs: list[tuple[int, any]] | None = None,
    write_error_attr_id: int | None = None,
) -> str:
    """Shared generator for measurement clusters. Adds WRITE_CASES and DISCOVER_CASES."""
    SEQ = 1
    read_pairs = [
        (
            read_attrs_request([measured_attr_id], SEQ),
            read_attrs_response(cluster_cls, {measured_attr_id: v}, SEQ),
        )
        for v in values
    ]
    for attr_id, val in (extra_read_attrs or []):
        read_pairs.append((
            read_attrs_request([attr_id], SEQ),
            read_attrs_response(cluster_cls, {attr_id: val}, SEQ),
        ))
    parts = [fmt_request_response_pairs("READ_CASES", read_pairs)]
    if write_error_attr_id is not None:
        write_pairs = [
            (
                write_attrs_request(cluster_cls, {write_error_attr_id: values[0]}, SEQ),
                write_attrs_response_error(write_error_attr_id, 0x88, SEQ),
            )
        ]
        parts.append(fmt_request_response_pairs("WRITE_CASES", write_pairs))
    parts.append(fmt_request_response_pairs("DISCOVER_CASES", _discover_cases(cluster_key, SEQ)))
    return assemble(*parts)


def gen_cluster_temperature() -> str:
    # extra: min=-2000, max=8000, tolerance=100
    return _gen_cluster_measurement(
        zcl_measurement.TemperatureMeasurement,
        measured_attr_id=0x0000,
        values=[0, 2500, -1000],
        cluster_key="temperature",
        extra_read_attrs=[(0x0001, -2000), (0x0002, 8000), (0x0003, 100)],
        write_error_attr_id=0x0000,
    )


def gen_cluster_humidity() -> str:
    # extra: min=100, max=9000, tolerance=100
    return _gen_cluster_measurement(
        zcl_measurement.RelativeHumidity,
        measured_attr_id=0x0000,
        values=[0, 5000, 9999],
        cluster_key="humidity",
        extra_read_attrs=[(0x0001, 100), (0x0002, 9000), (0x0003, 100)],
        write_error_attr_id=0x0000,
    )


def gen_cluster_pressure() -> str:
    # extra: min=0, max=2000, tolerance=100
    return _gen_cluster_measurement(
        zcl_measurement.PressureMeasurement,
        measured_attr_id=0x0000,
        values=[0, 1013, -1],
        cluster_key="pressure",
        extra_read_attrs=[(0x0001, 0), (0x0002, 2000), (0x0003, 100)],
        write_error_attr_id=0x0000,
    )


def gen_cluster_flow() -> str:
    # extra: min=0, max=1000, tolerance=100
    return _gen_cluster_measurement(
        zcl_measurement.FlowMeasurement,
        measured_attr_id=0x0000,
        values=[0, 100, 65534],
        cluster_key="flow",
        extra_read_attrs=[(0x0001, 0), (0x0002, 1000), (0x0003, 100)],
        write_error_attr_id=0x0000,
    )


def gen_cluster_illuminance() -> str:
    # extra: min=10, max=60000, tolerance=100
    return _gen_cluster_measurement(
        zcl_measurement.IlluminanceMeasurement,
        measured_attr_id=0x0000,
        values=[0, 1000, 65533],
        cluster_key="illuminance",
        extra_read_attrs=[(0x0001, 10), (0x0002, 60000), (0x0003, 100)],
        write_error_attr_id=0x0000,
    )


def gen_cluster_occupancy() -> str:
    # zigpy OccupancySensing attr model diverges from our impl (no 0x0002, different type for 0x0001)
    # so only 0x0000 (occupancy bitmap) is vector-tested via zigpy reference
    return _gen_cluster_measurement(
        zcl_measurement.OccupancySensing,
        measured_attr_id=0x0000,
        values=[0, 1],
        cluster_key="occupancy",
        write_error_attr_id=0x0000,
    )


def gen_cluster_level_control() -> str:
    SEQ = 1
    values = [0, 127, 254]
    read_pairs = [
        (
            read_attrs_request([0x0000], SEQ),
            read_attrs_response(zcl_general.LevelControl, {0x0000: v}, SEQ),
        )
        for v in values
    ]
    cmd_pairs = [
        # MoveToLevel (0x00): level, transition=0 (instant)
        *[
            (cluster_cmd_request(0x00, bytes([level, 0x00, 0x00]), SEQ), default_response(0x00, 0x00, SEQ))
            for level in values
        ],
        # MoveToLevelWithOnOff (0x04): same payload format
        (cluster_cmd_request(0x04, bytes([100, 0x00, 0x00]), SEQ), default_response(0x04, 0x00, SEQ)),
        # Move (0x01): Up, rate=50 units/s
        (cluster_cmd_request(0x01, bytes([0x00, 50]), SEQ), default_response(0x01, 0x00, SEQ)),
        # Step (0x02): Up, size=10, transition=0
        (cluster_cmd_request(0x02, bytes([0x00, 10, 0x00, 0x00]), SEQ), default_response(0x02, 0x00, SEQ)),
        # Stop (0x03): no payload
        (cluster_cmd_request(0x03, b"", SEQ), default_response(0x03, 0x00, SEQ)),
        # MoveWithOnOff (0x05): Up, rate=50
        (cluster_cmd_request(0x05, bytes([0x00, 50]), SEQ), default_response(0x05, 0x00, SEQ)),
        # StepWithOnOff (0x06): Up, size=10, transition=0
        (cluster_cmd_request(0x06, bytes([0x00, 10, 0x00, 0x00]), SEQ), default_response(0x06, 0x00, SEQ)),
        # StopWithOnOff (0x07): no payload
        (cluster_cmd_request(0x07, b"", SEQ), default_response(0x07, 0x00, SEQ)),
    ]
    write_pairs = [
        (write_attrs_request(zcl_general.LevelControl, {0x0000: 127}, SEQ),
         write_attrs_response_error(0x0000, 0x88, SEQ)),
    ]
    return assemble(
        fmt_request_response_pairs("READ_CASES", read_pairs),
        fmt_request_response_pairs("COMMAND_CASES", cmd_pairs),
        fmt_request_response_pairs("WRITE_CASES", write_pairs),
        fmt_request_response_pairs("DISCOVER_CASES", _discover_cases("level_control", SEQ)),
    )


def gen_cluster_basic() -> str:
    SEQ = 1
    # Fixed static config: zcl_version=3, power_source=0x01, device_enabled varies.
    read_pairs = [
        (read_attrs_request([0x0000], SEQ), read_attrs_response(zcl_general.Basic, {0x0000: 3}, SEQ)),
        (read_attrs_request([0x0007], SEQ), read_attrs_response(zcl_general.Basic, {0x0007: 0x01}, SEQ)),
        (read_attrs_request([0x0012], SEQ), read_attrs_response(zcl_general.Basic, {0x0012: False}, SEQ)),
        (read_attrs_request([0x0012], SEQ), read_attrs_response(zcl_general.Basic, {0x0012: True}, SEQ)),
    ]
    # Write device_enabled=True → Success; write zcl_version (read-only) → ReadOnly (0x88)
    write_pairs = [
        (write_attrs_request(zcl_general.Basic, {0x0012: True}, SEQ), write_attrs_response_success(SEQ)),
        (write_attrs_request(zcl_general.Basic, {0x0000: 99}, SEQ), write_attrs_response_error(0x0000, 0x88, SEQ)),
    ]
    return assemble(
        fmt_request_response_pairs("READ_CASES", read_pairs),
        fmt_request_response_pairs("WRITE_CASES", write_pairs),
        fmt_request_response_pairs("DISCOVER_CASES", _discover_cases("basic", SEQ)),
    )


def gen_cluster_electrical() -> str:
    SEQ = 1
    scenarios = [
        {0x0505: 0, 0x0508: 0, 0x050B: 0},
        {0x0505: 230, 0x0508: 1000, 0x050B: 100},
    ]
    read_pairs = [
        (
            read_attrs_request([0x0505, 0x0508, 0x050B], SEQ),
            read_attrs_response(zcl_homeautomation.ElectricalMeasurement, attrs, SEQ),
        )
        for attrs in scenarios
    ]
    # measurement_type (0x0000, Bitmap32): SinglePhaseAC = bit 3 set (0x0000_0008)
    read_pairs.append((
        read_attrs_request([0x0000], SEQ),
        read_attrs_response(zcl_homeautomation.ElectricalMeasurement, {0x0000: 0x0000_0008}, SEQ),
    ))
    write_pairs = [
        (write_attrs_request(zcl_homeautomation.ElectricalMeasurement, {0x0505: 100}, SEQ),
         write_attrs_response_error(0x0505, 0x88, SEQ)),
    ]
    return assemble(
        fmt_request_response_pairs("READ_CASES", read_pairs),
        fmt_request_response_pairs("WRITE_CASES", write_pairs),
        fmt_request_response_pairs("DISCOVER_CASES", _discover_cases("electrical", SEQ)),
    )


def gen_cluster_thermostat() -> str:
    SEQ = 1
    # READ_CASES: local_temp=2150, cooling_setpoint=2600 (default), heating_setpoint=2000 (default)
    read_pairs = [
        (read_attrs_request([0x0000], SEQ), read_attrs_response(zcl_hvac.Thermostat, {0x0000: 2150}, SEQ)),
        (read_attrs_request([0x0011], SEQ), read_attrs_response(zcl_hvac.Thermostat, {0x0011: 2600}, SEQ)),
        (read_attrs_request([0x0012], SEQ), read_attrs_response(zcl_hvac.Thermostat, {0x0012: 2000}, SEQ)),
    ]
    # COMMAND_CASES: SetpointRaiseLower (0x00) — payload [mode u8, amount i8]
    cmd_pairs = [
        (cluster_cmd_request(0x00, bytes([0x00, 5]), SEQ), default_response(0x00, 0x00, SEQ)),       # Heat +5
        (cluster_cmd_request(0x00, bytes([0x01, 0xFD]), SEQ), default_response(0x00, 0x00, SEQ)),    # Cool -3
        (cluster_cmd_request(0x00, bytes([0x02, 2]), SEQ), default_response(0x00, 0x00, SEQ)),       # Both +2
    ]
    write_pairs = [
        (write_attrs_request(zcl_hvac.Thermostat, {0x0011: 2400}, SEQ), write_attrs_response_success(SEQ)),
        (write_attrs_request(zcl_hvac.Thermostat, {0x0000: 2000}, SEQ), write_attrs_response_error(0x0000, 0x88, SEQ)),
    ]
    return assemble(
        fmt_request_response_pairs("READ_CASES", read_pairs),
        fmt_request_response_pairs("COMMAND_CASES", cmd_pairs),
        fmt_request_response_pairs("WRITE_CASES", write_pairs),
        fmt_request_response_pairs("DISCOVER_CASES", _discover_cases("thermostat", SEQ)),
    )


GENERATORS: dict[str, tuple[str, callable]] = {
    # (output filename, generator function)
    "u8":                ("u8.rs",                 lambda: gen_uint(t.uint8_t,  "u8",  8)),
    "u16":               ("u16.rs",                lambda: gen_uint(t.uint16_t, "u16", 16)),
    "u32":               ("u32.rs",                lambda: gen_uint(t.uint32_t, "u32", 32)),
    "u64":               ("u64.rs",                lambda: gen_uint(t.uint64_t, "u64", 64)),
    "i8":                ("i8.rs",                 lambda: gen_sint(t.int8s,    "i8",  8)),
    "i16":               ("i16.rs",                lambda: gen_sint(t.int16s,   "i16", 16)),
    "i32":               ("i32.rs",                lambda: gen_sint(t.int32s,   "i32", 32)),
    "i64":               ("i64.rs",                lambda: gen_sint(t.int64s,   "i64", 64)),
    "bool":              ("bool.rs",               gen_bool),
    "f32":               ("f32.rs",                gen_f32),
    "f64":               ("f64.rs",                gen_f64),
    "bitmap8":           ("bitmap8.rs",            lambda: gen_bitmap(t.bitmap8,  "Bitmap8",  "u8",  8)),
    "bitmap16":          ("bitmap16.rs",           lambda: gen_bitmap(t.bitmap16, "Bitmap16", "u16", 16)),
    "bitmap32":          ("bitmap32.rs",           lambda: gen_bitmap(t.bitmap32, "Bitmap32", "u32", 32)),
    "bitmap64":          ("bitmap64.rs",           lambda: gen_bitmap(t.bitmap64, "Bitmap64", "u64", 64)),
    "enum8":             ("enum8.rs",              gen_enum8),
    "enum16":            ("enum16.rs",             gen_enum16),
    "short_text":        ("short_text.rs",         gen_short_text),
    "short_octet_string":("short_octet_string.rs", gen_short_octet_string),
    # Collection matrix — Array × element type
    "coll_array_u8":   ("collections/array_u8.rs",  lambda: gen_collection(
        0x20, 1, lambda v: t.uint8_t(v).serialize(), "u8", "u8",
        [[], [42], [1, 100, 0xFE]], 0x21)),
    "coll_array_u16":  ("collections/array_u16.rs", lambda: gen_collection(
        0x21, 2, lambda v: t.uint16_t(v).serialize(), "u16", "u16",
        [[], [1], [1, 2, 3]], 0x20)),
    "coll_array_i16":  ("collections/array_i16.rs", lambda: gen_collection(
        0x29, 2, lambda v: t.int16s(v).serialize(), "i16", "i16",
        [[], [-1], [0, 100, -100]], 0x20)),
    "coll_array_bool": ("collections/array_bool.rs", lambda: gen_collection(
        0x10, 1, lambda v: t.Bool(v).serialize(), "bool", "",
        [[], [True], [False, True, False]], 0x20)),
    # Collection matrix — Bag × element type (same wire format, different schema kind)
    "coll_bag_u8":     ("collections/bag_u8.rs",  lambda: gen_collection(
        0x20, 1, lambda v: t.uint8_t(v).serialize(), "u8", "u8",
        [[], [42], [1, 100, 0xFE]], 0x21)),
    "coll_bag_u16":    ("collections/bag_u16.rs", lambda: gen_collection(
        0x21, 2, lambda v: t.uint16_t(v).serialize(), "u16", "u16",
        [[], [1], [1, 2, 3]], 0x20)),
    # Collection matrix — Set × element type (uniqueness enforced)
    "coll_set_u8":     ("collections/set_u8.rs",  lambda: gen_collection_set(
        0x20, lambda v: t.uint8_t(v).serialize(), "u8", "u8",
        [[1, 2], [10, 11, 12]], [1, 1])),
    "coll_set_u16":    ("collections/set_u16.rs", lambda: gen_collection_set(
        0x21, lambda v: t.uint16_t(v).serialize(), "u16", "u16",
        [[1, 2], [10, 20, 30]], [1, 1])),
    # Struct: (u8, u16) pair with StructEncoder/StructDecoder
    "coll_struct_pair": ("collections/struct_pair.rs", gen_collection_struct_pair),
    # Nesting: ArrayOf<ArrayOf<u8>>, ArrayOf<StructOf<PairStruct>>, struct with array field
    "coll_nested_array_u8":      ("collections/array_of_array_u8.rs",  gen_nested_array_u8),
    "coll_array_of_struct_pair": ("collections/array_of_struct_pair.rs", gen_array_of_struct_pair),
    "coll_struct_with_array":    ("collections/struct_with_array.rs",   gen_struct_with_array),
    # Cluster vectors — ZCL frame (request, response) pairs from zigpy reference impl
    "cluster_on_off":      ("clusters/on_off.rs",      gen_cluster_on_off),
    "cluster_temperature": ("clusters/temperature.rs", gen_cluster_temperature),
    "cluster_humidity":    ("clusters/humidity.rs",    gen_cluster_humidity),
    "cluster_pressure":    ("clusters/pressure.rs",    gen_cluster_pressure),
    "cluster_flow":        ("clusters/flow.rs",        gen_cluster_flow),
    "cluster_illuminance": ("clusters/illuminance.rs", gen_cluster_illuminance),
    "cluster_occupancy":     ("clusters/occupancy.rs",     gen_cluster_occupancy),
    "cluster_level_control": ("clusters/level_control.rs", gen_cluster_level_control),
    "cluster_basic":         ("clusters/basic.rs",         gen_cluster_basic),
    "cluster_electrical":    ("clusters/electrical.rs",    gen_cluster_electrical),
    "cluster_thermostat":    ("clusters/thermostat.rs",    gen_cluster_thermostat),
}

def write_or_check(path: Path, content: str, check: bool) -> bool:
    """Return True if content matches what is on disk (or was written). False if drift."""
    if check:
        existing = path.read_text() if path.exists() else ""
        if existing == content:
            return True
        diff = difflib.unified_diff(
            existing.splitlines(keepends=True),
            content.splitlines(keepends=True),
            fromfile=str(path),
            tofile="generated",
        )
        sys.stderr.write("".join(diff))
        return False
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True, type=Path, help="Output directory")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Diff against existing files; exit 1 if any differ (no writes)",
    )
    args = parser.parse_args()

    ok = True
    for name, (filename, gen_fn) in GENERATORS.items():
        try:
            content = gen_fn()
        except Exception as exc:
            print(f"  ERROR {name}: {exc}", file=sys.stderr)
            ok = False
            continue

        dest = args.out / filename
        if write_or_check(dest, content, args.check):
            if not args.check:
                print(f"  wrote {dest}")
        else:
            print(f"  DRIFT {dest}", file=sys.stderr)
            ok = False

    if not ok and args.check:
        print(
            "\nVectors out of date — run `cargo xtask generate-vectors` to refresh.",
            file=sys.stderr,
        )
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
